server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: offer-service
          uri: lb://offer-service
          predicates:
            - Path=/offer/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
